# Exclude SwiftPM dependencies from linting
excluded:
  - .build

disabled_rules:
  - force_try
  - multiple_closures_with_trailing_closure
  - todo
  - trailing_comma

identifier_name:
  min_length: 2
